<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Confirm your email</title>
</head>
<body>
    <h1>Congratulations! You successfully registered!</h1>
    <br>
    <h3>In order to use CodeP, the best html/css/js online code platform,</h3>
    <br>
    <h3>please proceed to your email (${email}), to confirm your account </h3>
    <br>
    <h3>The message will be there in no time! Thank you for registering</h3>
</body>
</html>