<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
    <h1>Thank you for your registration!</h1>
    <p><h3>In order to proceed with using CodeP, you have to confirm your email </h3></p>
    <br>
    <p>You can do that by using this link: ${url}</p>
    <br>
    <p>If you didn't registered at http://codep.com, please ignore this message</p>
</body>
</html>