POST /api/1.0/login
Host: localhost:8080
Content-Type: application/json

{
  "nickname": "MuziCunt",
  "password": "123"
}
###

POST /api/1.0/register
Host: localhost:8080
Content-Type: application/json

{
  "nickname": "Sergey",
  "password": "228",
  "confirmPassword": "228",
  "email": "test@gmail.com"
}
###

POST /api/1.0/login
Host: localhost:8080
Content-Type: application/json

{
  "email": "mikheevs11@gmail.com",
  "password": "123"
}
###

POST /messages
Host: localhost:8080
Content-Type: application/json

{
  "pageId": "FIRST",
  "text": "hello!"
}

###
GET /messages
Host: localhost:8080
Content-Type: application/json

{
  "pageId": "FIRST_PAGE"
}

###